name: Waka Readme

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README 
    runs-on: ubuntu-latest
    steps:
      - uses: ChenqiaoStation/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          LOCALE: TRUE
          COMMIT_BY_ME: TRUE
          COMMIT_MESSAGE: TRUE
          SHOW_UPDATED_DATE: TRUE
          SHOW_LINES_OF_CODE: TRUE
          SHOW_PROFILE_VIEWS: TRUE
